spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /images/**
  resources:
    static-locations: file:${settings.workspace}/

  liquibase:
    enabled: true


server:
  servlet:
    context-path: /file

settings:
  workspace: C://Users//XPS//Pictures
  upload-path: ${settings.workspace}//fileUpload
  database-path: ~/.h2



---
spring:
  profiles: dev
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:${settings.database-path}/file-cloud
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

