spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:~/h2/test
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    platform: h2
#    data: classpath:db/data.sql
#    schema: classpath:db/schema.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /images/**
  resources:
    static-locations: file:C://Users//XPS//Pictures/