spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /images/**
  resources:
    static-locations: file:C://Users//XPS//Pictures/

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml


server:
  servlet:
    context-path: /file


---
spring:
  profiles: dev
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:~/.h2/test
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update