CREATE TABLE IF NOT EXISTS FILE
(
  FILE_ID     VARCHAR(40) NOT NULL PRIMARY KEY,
  FILE_NAME   VARCHAR(100) COMMENT '文件名',
  FILE_PATH   VARCHAR(100) COMMENT '文件保存的路径（相对路径）',
  FILE_SIZE   INT COMMENT '文件总大小',
  CREATE_TIME DATE,
  MODIFY_TIME DATE
);

CREATE TABLE IF NOT EXISTS SLICE_LOG
(
  ID          INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ETAG        VARCHAR(100) NOT NULL COMMENT '文件唯一标识',
  NAME        VARCHAR(100) NOT NULL COMMENT '文件名',
  FIRST       BOOLEAN COMMENT '是否第一片',
  LAST        BOOLEAN COMMENT '是否最后一片',
  DIR         VARCHAR(100) COMMENT '文件保存的目录',
  SIZE        INT COMMENT '文件总大小',
  INDEX       INT COMMENT '分片序号',
  SLICE_SIZE  INT COMMENT '分片大小',
  CREATE_TIME DATE
);